### PR TITLE
fix bug related to missing contact_method information in some cases

### PR DESCRIPTION
**Pull request by Battula**
ME-180463890

### CODE REVIEW

**Review by markgoho — CHANGES_REQUESTED** [review]
please update PR title to be less generic

**Comment by Battula** [comment]
@markgoho like ?

**Comment by markgoho** [comment]
@Battula this is up to you as the developer to describe your changes in a way that conveys meaning and summarizes what's changing about the code

what you've written amounts to "made changes" -- yeah, okay, that's what a PR does, but what changes are you making?

If you're finding it difficult to summarize the changes, it's possible you've put too much in the PR and it needs to be broken out  in to separate changes, each able to be independently reviewed

**Comment by Battula** [comment]
@markgoho I have already summarized the list of changes in the commit message. 

If you're finding it difficult to see the list of changes that I made, please click [here](https://github.com/ideacrew/polypress/pull/27/commits/3d2ea17cacae3b85a627bc048460060d0f061d69).

The changes aren't too big to break them down in separate PRs. Thanks

**Comment by markgoho** [comment]
@Battula I'm not finding it difficult to understand the changes, I'm finding it difficult to see how "made changes" properly summarizes a number of distinct changes

options:
1. find a better title that better summarizes the changes
2. break the PR up into multiple PRs

**Comment by Battula** [comment]
@markgoho I can't summarize all the changes in the PR title, so I came up with a generic title and summarized the changes in the comment section.

**Comment by markgoho** [comment]
@Battula please submit PRs for each of these:
- Updated aca_entities gem version
- Updated preview payload to include health and dental enrollments
- Fixed bug related to missing contact_method information in some cases
- Updated verabiage for Cub Care in application settings

**Comment by Battula** [comment]
@markgoho What's wrong with this pull request ?

**Comment by markgoho** [comment]
@Battula this PR clearly combines 4 different changes to the codebase that each need their own PR

here are the PRs I expect to see:
- Updated aca_entities gem version
- Updated preview payload to include health and dental enrollments
- Fixed bug related to missing contact_method information in some cases
- Updated verabiage for Cub Care in application settings

**Comment by Battula** [comment]
All the changes are related to FRE notice, and I don't see why they can't be on a single pull request. @markgoho 
They aren't too big to split them into separate PRs.

**Review by harshaellanki — APPROVED** [review]

**Comment by Battula** [comment]
@markgoho Please don't close this PR, we need this to be merged to trunk. Thank you!

**Review by markgoho — APPROVED** [review]

**Pull request merged**
